### ISSUE TITLE
[Bug]: column width

### ISSUE THREAD

**Issue by ameinhardt** [DerYeger/vue-masonry-wall#70] opened 2022-11-22 13:56 UTC
### Description

My cards are stretching beyond the window width

### Reproduction

On demo page https://vue-masonry-wall.yeger.eu/ :
1. set width: 1000px on `.masonry-item > .item.accent` and adjust the window width
2. add `min-width: 1px` to `.masonry-column` and adjust the window width

### Additional context

Set `.masonry-column {
  min-width: 1px;
}` to not exceed the container width

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment] 2022-11-22 14:06
This is not a bug, but an incorrect usage of the library.
As stated in the README: 

> All columns have the same width, specified by the column-width property. In addition, the elements of items should not set a specific width and instead be full-width, e.g., use width: 100%.

I.e., do not set the width of elements to something not percentage based. The width of columns is calculated automatically, so use percentage widths (usually 100% to get the right `gap`).

**Comment by ameinhardt** [comment] 2022-11-22 14:26
fixed width was just a simplified example. Children of the `item` might exceed for some reason (dynamic content, picture etc.) the maximum intended  width. Then, flex stretches instead of limiting the size and applying overflow scroll, as long there's no min-width set.

**Comment by DerYeger** [comment] 2022-11-23 13:05
I see the issue now, it should be fixed in v3.3.1.

Just keep in mind that the overflow is still present and has to be handled by your item.
I cannot hide the overflow in the library, because that would also break effects such as the shadow used in the demo.

**Closed by DerYeger** 2022-11-23 13:05 UTC
Labels: bug, question
